### ISSUE TITLE
How to parse GPGSA?

### ISSUE THREAD

**Issue by c1394393468** [lgaticaq/node-nmea#147]
Can node-nmea support these?

 GGA ,GLL,GSA,GSV,RMC,VTG,ZDA

And
GP ,GN , GL ,BD
1. The prefix identifier “GP” refers to the GPS global navigation system;
2. Prefix identification “GN” refers to the GNSS global navigation system (collectively referred to as various global navigation systems); 
3. Prefix identification “GL” refers to the GLONASS global navigation system;
4. Prefix identifier “BD” refers to the BeiDou global navigation system.

**Comment by lgaticaq** [comment]
Maybe it's easy to implement but I'm not keeping it very often anymore. But feel free to fork the repository to make the changes and include them in the library.
