### ISSUE TITLE
Parse not working on IPhone logger nmea string

### ISSUE THREAD

**Issue by flaviostutz** [lgaticaq/node-nmea#15]
I used an IPhone App to log nmea messages and the parser didn't recognize those lines as valid.

**Comment by lgaticaq** [comment]
Hello, add sample data

**Comment by flaviostutz** [comment]
$GPRMC,084200.00,A,1559.7695,S,4749.3789,W,2.2,128.3,181016,0.0,E,A*0d
$GPRMC,091245.00,A,1559.6838,S,4749.4203,W,0.0,144.5,181016,0.0,E,A*0c
$GPRMC,091404.00,A,1559.6815,S,4749.4234,W,0.0,300.9,181016,0.0,E,A*0a
$GPRMC,091405.00,A,1559.6815,S,4749.4234,W,0.0,300.9,181016,0.0,E,A*0b
$GPRMC,091507.00,A,1559.6807,S,4749.4242,W,0.0,151.9,181016,0.0,E,A*0c
$GPGGA,091407.00,1559.6815,S,4749.4234,W,12,12,2.0,913.5,M,0.0,M,0.0,0000*76
$GPGGA,091406.00,1559.6815,S,4749.4234,W,12,12,2.0,913.4,M,0.0,M,0.0,0000*76
$GPGGA,091404.00,1559.6815,S,4749.4234,W,12,12,2.0,913.3,M,0.0,M,0.0,0000*73
$GPGGA,090523.00,1559.6957,S,4749.5053,W,12,12,1.0,912.4,M,0.0,M,0.0,0000*76

**Comment by lgaticaq** [comment]
Sorry but that data is not in the correct format. That is why my parser identifies them as invalid.
