### ISSUE TITLE
Wrong magnetic variation and cordinates

### ISSUE THREAD

**Issue by lukavia** [lgaticaq/node-nmea#3]
on the following input: 
$GPRMC,102939.000,A,4241.2649,N,02318.6959,E,2.87,50.45,260815,,*33
the parse funcition returns: 
{ raw: '$GPRMC,102939.000,A,4241.2649,N,02318.6959,E,2.87,50.45,260815,,*33',
  type: 'RMC',
  datetime: Wed Aug 26 2015 13:29:39 GMT+0300 (EEST),
  loc: 
   { type: 'Point',
     coordinates: [ 23.311598333333336, 42.68774833333334 ] },
  speed: 5.31524,
  track: '50.45',
  magneticVariation: ',',
  mode: null }

Here magnetic variation should be empty since it is missing in the line. 

The cordinates seams to suffer from floating  point rounding problem, but I'm not sure if this is a real problem. 
Since I want to store those in DB I think there should be an option to chose how the cordinates and speed should be transformed. 

Great work.

**Comment by lgaticaq** [comment]
Fix magneticVariation.
About the coordinates and speed say it optional stored as string or float?

**Comment by lukavia** [comment]
I should have been more clear. 
For the rounding, may be you should consider using library like http://mathjs.org/ to avoid it. 
For the type I meant, that someone can need the values in miles or something else. I think you should add an option to specify how to translate the values. 
I think for fast solution you can state in the docs that the values are always returned in km and cordinates in decimals, so anyone using the library doesn't have to browse the code and will be sure that this wont change in some update. 

This request however is a miner issue, so if you are busy just close it.
