### ISSUE TITLE
When there is no valid fix the messege is not parsed

### ISSUE THREAD

**Issue by lukavia** [lgaticaq/node-nmea#7]
Today the gps returned the folloing string: 
$GPRMC,150449.000,L,4239.5210,N,02318.7727,E,39.75,326.93,040915,,*38

parse function decode this to: 
{ raw: '$GPRMC,150449.000,L,4239.5210,N,02318.7727,E,39.75,326.93,040915,,*38',
  valid: false } 
Although there is no valid GPS fix from the satellite the data still can be parsed and the coordinates set

**Comment by lgaticaq** [comment]
The state L to mean?. I only know the states A (active) or V (void)

**Comment by lukavia** [comment]
Hm.... I not really sure actually. In the device comunicataion manual it is state that only A and V are returned. May be it is a bug in the device, but I think it would be better for the data to still be parsed and the state to be; Unknow instead of nothing.
